apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.name }}
  namespace: {{ .Values.mysql.namespace }}
type: Opaque
data: 
  #base64 encrypted format
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.password | b64enc }}
  db_password: {{ .Values.mysql.password | b64enc }}

---
apiVersion: v1
kind: Secret
metadata: 
  name: {{ .Values.mysql.name }}
  namespace: {{ .Values.wordpress.namespace }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.password | b64enc }}
  db_password: {{ .Values.mysql.password | b64enc }}
