apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: database
type: Opaque
data: 
  #base64 encrypted format
  MYSQL_ROOT_PASSWORD: YWlqYW5h
  db_password: YWlqYW5h

---
apiVersion: v1
kind: Secret
metadata: 
  name: mysql
  namespace: web
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YWlqYW5h
  db_password: YWlqYW5h
