apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: wordpress
  name: wordpress
  namespace: web
spec:
  ports:
    - port: 80
  selector:
    name: wordpress
  type: LoadBalancer

---

apiVersion: v1
kind:  Service
metadata: 
  labels:
    name: mysql
  name: mysql
  namespace: database
spec:
  ports:
    - port: 3306
  selector:
    name: mysql
  type: ClusterIP





