apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: web
  labels:
    name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      name: wordpress
  template:
    metadata:
      labels:
        name: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:6.2.1-apache
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 80
            name: wordpress
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          volumeMounts: 
            - name: wordpress-ebs
              mountPath: /var/www/html
          env: 
            - name: WORDPRESS_DB_HOST
              value: mysql.database.svc.cluster.local
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: MYSQL_ROOT_PASSWORD
            - name: WORDPRESS_DB_USER
              value: wordpress
      volumes:
        - name: wordpress-ebs
          persistentVolumeClaim:
            claimName: wordpress-pvc




  








